resolver: lts-20.14
packages:
- '.'
extra-deps:
- streamly-core-0.1.0

#extra-deps:
#- unicode-data-0.3.0
#- lockfree-queue-0.2.4
#- github: composewell/streamly
#  commit: "9596aea3ab33d3c2fa513247fcfe8604bd7ff454"
#- github: composewell/streamly
#  commit: "9596aea3ab33d3c2fa513247fcfe8604bd7ff454"
#  subdirs:
#    - core
#- github: composewell/streamly-process
#  commit: "d80b860d9d8ea98e4f7f63390442b3155c34dd08"

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
