resolver: lts-22.33
packages:
- '.'
#extra-deps:
#  - streamly-core-0.3.0
#  - streamly-0.11.0

extra-deps:
- github: composewell/streamly
  commit: "4e2fccbe2a6a4c168801fffcdb17aaec1466f838"
- github: composewell/streamly
  commit: "4e2fccbe2a6a4c168801fffcdb17aaec1466f838"
  subdirs:
    - core

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
